---
version: 2

workflows:
  version: 2
  build_linux:
    jobs:
      - pigen

jobs:
  pigen:
    working_directory: ~/work
    machine:
      image: circleci/classic:latest

    steps:
      - checkout
      - run: sudo apt update &&
          sudo apt install -y --no-install-recommends
            qemu-user-static
            dosfstools
            libconfuse-dev genext2fs mtools
      - run:
            name: Setup Environment Variables
            command: |
                    echo 'export mirror="http://dl-cdn.alpinelinux.org/alpine/"' >> $BASH_ENV
                    echo 'export apk_version=2.10.1-r0' >> $BASH_ENV

      # install genimage
      - run: wget https://github.com/pengutronix/genimage/releases/download/v10/genimage-10.tar.xz
      - run: tar xf genimage-10.tar.xz
      - run: cd genimage-10 && ./configure && make && sudo make install
      - run: echo mtools_skip_check=1 > ~/.mtoolsrc # weird workaround

      # https://wiki.alpinelinux.org/wiki/Installing_Alpine_Linux_in_a_chroot
      - run: wget ${mirror}/latest-stable/main/x86_64/apk-tools-static-${apk_version}.apk
      - run: tar -xzf apk-tools-static-*.apk
      - run: sudo ./sbin/apk.static -X ${mirror}/latest-stable/main -U --allow-untrusted --root ~/chroot --arch=armhf --initdb add apk-tools alpine-keys

      # stupid setup stuff
      - run: echo http://dl-cdn.alpinelinux.org/alpine/v3.8/main | sudo tee ~/chroot/etc/apk/repositories
      - run: echo nameserver 4.2.2.2 | sudo tee ~/chroot/etc/resolv.conf
      - run: sudo mkdir -p ~/chroot/usr/bin
      - run: sudo cp /usr/bin/qemu-arm-static ~/chroot/usr/bin

      - run: sudo chroot ~/chroot /sbin/apk -- add alpine-base linux-rpi2

      # package into sdcard image
      - run: sudo genimage --rootpath ~/chroot

      - store_artifacts:
          path: ~/work/images/sdcard.img
          destination: deploy
